.PHONY: version
version:
	redshift -V

.PHONY: install
install:
	sudo apt-get install redshift redshift-gtk

.PHONY: autostart
autostart:
	cp redshift-gtk.desktop ~/.config/autostart/
	cp redshift.conf ~/.config/
